kind: MLApp
metadata:
  name: gans-in-action
spec:
  package_manager: "pip{{.python_version.value}}"
  packages:
  - names:
    {{- range $i, $value := .packages }}
    - "{{ $value }}"
    {{- end }}
    manager: "pip{{.python_version.value}}"
  default_mount_path: "/notebooks"
  tasks:
  - name: run-chapter
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      images:
        cpu: "kuberlab/tensorflow:cpu-36-1.14-full"
        gpu: "kuberlab/tensorflow:gpu-36-1.14-full"
      command: "jupyter nbconvert chapter-2/Chapter_2_Autoencoder.ipynb --execute --to html --stdout --ExecutePreprocessor.timeout=-1 | python tools/submit_report.py"
      workdir: "$CHAPTERS_DIR"
      resources:
        accelerators:
        {{- if .useGPU.value }}
          gpu: 1
        {{- else }}
          gpu: 0
        {{- end }}
        requests:
          cpu: "1"
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 4Gi
      default_volume_mapping: true
  uix:
  - name: jupyter
    displayName: Jupyter
    images:
      cpu: "kuberlab/tensorflow:cpu-36-1.14-full"
      gpu: "kuberlab/tensorflow:gpu-36-1.14-full"
    resources:
      accelerators:
      {{- if .useGPU.value }}
        gpu: 1
      {{- else }}
        gpu: 0
      {{- end }}
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    default_volume_mapping: true
  volumes:
  - gitRepo:
      repository: {{ gitRepo .chapters.value }}
      accountId: '{{ .chapters.accountId }}'
      revision: '{{ .chapters.revision }}'
    isLibDir: false
    name: chapters
    subPath: {{ gitSubPath .chapters.value }}
  - isLibDir: true
    name: lib
    clusterStorage: {{ .storage.value }}
  - mountPath: /notebooks
    name: code
    subPath: code
    clusterStorage: {{ .storage.value }}
  - mountPath: /dev/shm
    name: shared
    emptyDir:
      sizeLimit: 8096Mi
      medium: Memory